# Generated by Django 3.1.6 on 2021-02-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='Имя друга')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.TextField(verbose_name='Телефон')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='friends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='p_library.friend'),
        ),
    ]
